spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hans_base?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 1000
      max-idle: 10
      max-total: 50
      initial-size: 10
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

swagger:
  title: demo
  description: 接口测试
  contact:
    url: 韩帅
    email: hanhshuai@163.com
  version: 1.0
